name: gofmt

on: [pull_request]

jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: reviewdog / gofmt
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: '--disable-all -E gofmt,goimports'
          fail_on_error: true
          level: error
          reporter: github-pr-review
          filter_mode: file